version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - test_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - test_network

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - test_network
    ports:
      - "5432:5432"
networks:
  test_network:

volumes:
  db_data:
